// https://docs.patreon.com/#benefit

import { RelationshipObject, ResourceObject } from 'include-json-api';
import { APICampaign } from './campaign';
import { APIDeliverable } from './deliverable';
import { APITier } from './tier';

export interface APIBenefit extends ResourceObject {
    type: 'benefit';
    attributes: {
        /**
         * The third-party external ID this reward is associated with, if any.
         */
        app_external_id: string | null;
        /**
         * Any metadata the third-party app included with this benefit on creation.
         */
        app_meta: object | null;
        /**
         * Type of benefit, such as `custom` for creator-defined benefits.
         */
        benefit_type: string | null;
        /**
         * Datetime this benefit was created.
         * UTC ISO format
         */
        created_at: string;
        /**
         * Number of deliverables for this benefit that are due today specifically.
         */
        deliverables_due_today_count: number;
        /**
         * Number of deliverables for this benefit that have been marked complete.
         */
        delivered_deliverables_count: number;
        /**
         * Benefit display description.
         */
        description: string | null;
        /**
         * `true` if this benefit has been deleted.
         */
        is_deleted: boolean;
        /**
         * `true` if this benefit is no longer available to new patrons
         */
        is_ended: boolean;
        /**
         * `true` if this benefit is ready to be fulfilled to patrons.
         */
        is_published: boolean;
        /**
         * The next due date (after EOD today) for this benefit.
         * UTC ISO format
         */
        next_deliverable_due_date: string | null;
        /**
         * Number of deliverables for this benefit that are due, for all dates.
         */
        not_delivered_deliverables_count: number;
        /**
         * A rule type designation, such as `eom_monthly` or `one_time_immediate`.
         */
        rule_type: string | null;
        /**
         * Number of tiers containing this benefit.
         */
        tiers_count: number;
        /**
         * Benefit display title.
         */
        title: string;
    };
    relationships: {
        /**
         * The Campaign the benefit belongs to
         */
        campaign: { data: APICampaign };
        /**
         * (Alpha) The campaign-app connection
         */
        campaign_installation: RelationshipObject /* { data: APICampaignInstallation } */;
        /**
         * The Deliverables that have been generated by the Benefit
         */
        deliverables: { data: APIDeliverable[] };
        /**
         * The Tiers the benefit has been added to.
         */
        tiers: { data: APITier[] };
    };
}
